[tool.poetry]
name = "hsol-info"
version = "0.1.0"
description = ""
authors = ["molmoty <molmoty@gmail.com>"]
readme = "README.md"
packages = [{include = "hsol"}]

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
